### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-frontend#121]
The application will be protected with authentication provided by [auth0](https://auth0.com/).
We'll be using their default login overlay styled to match RRA (@ricardomestre).
All pages, except maybe About and Help need to be protected.

We need to include a login and logout buttons and information about the currently logged in user. Coordinate with @ricardomestre for the design of these 3 elements.

**Comment by olafveerman** [comment]
To support offline, authentication is optional and probably default(?).
