### ISSUE TITLE
Map tweaks

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/ram-frontend#127]
Improvements to the map:

- [x] use buckets (quintiles) for population size
- [x] add legend for population size
- [x] add tooltips

**Comment by danielfdsilva** [comment]
This is the process I used to implement the quintiles:
```
- Get total number of items
- Divide by 5 to get the size of the bucket.
- Order all the values and get the boundaries for the 5 buckets.
```
This way we ensure that all the buckets have the same number of values, but not the same distance between values. For example for the Sergipe fixtures these are the buckets:
```
[ 40555, 48875, 57967, 69392, 90445 ]
```
This produces the following result:
![image](https://user-images.githubusercontent.com/1090606/29176305-5d0f45b8-7de3-11e7-905a-ab6cbe0bb149.png)

@olafveerman Does this look ok? At the moment I'm using an increment of 5 radius for each bucket. This probably has to be revised and we need to add more breakpoints for other zoom levels.

cc @ricardomestre

**Comment by danielfdsilva** [comment]
I'm not sure what kind of legend we can use to explain the population size. We can display the bucket values but how do we convey the corresponding size?
@ricardomestre ideas?

**Comment by ricardomestre** [comment]
Fixed in https://github.com/WorldBank-Transport/ram-frontend/tree/feature/map-tweaks

**Comment by olafveerman** [comment]
All done with the tweaks. More map improvements to come in #144
