### ISSUE TITLE
Connect profile editor to the API

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-frontend#191]
The functionality for the profile editor is built ([style pending](https://github.com/WorldBank-Transport/ram-frontend/issues/190)) and currently using some dummy, hardcoded data to power the form. Once the [api is fully built](https://github.com/WorldBank-Transport/ram-backend/issues/229) the editor needs to be connected to it for data fetching and posting.

**Comment by olafveerman** [comment]
Implemented.
